#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xA5E9288C4FA415FA (jan.steffens@gmail.com)
#
Name     : rtkit
Version  : 0.13
Release  : 6
URL      : https://github.com/heftig/rtkit/releases/download/v0.13/rtkit-0.13.tar.xz
Source0  : https://github.com/heftig/rtkit/releases/download/v0.13/rtkit-0.13.tar.xz
Source1  : https://github.com/heftig/rtkit/releases/download/v0.13/rtkit-0.13.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 MIT
Requires: rtkit-bin = %{version}-%{release}
Requires: rtkit-data = %{version}-%{release}
Requires: rtkit-libexec = %{version}-%{release}
Requires: rtkit-man = %{version}-%{release}
Requires: rtkit-services = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libcap-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : sed
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0005-rtkit-daemon-Don-t-log-debug-messages-by-default.patch

%description
REALTIMEKIT Realtime Policy and Watchdog Daemon
GIT:
https://github.com/heftig/rtkit

%package bin
Summary: bin components for the rtkit package.
Group: Binaries
Requires: rtkit-data = %{version}-%{release}
Requires: rtkit-libexec = %{version}-%{release}
Requires: rtkit-services = %{version}-%{release}

%description bin
bin components for the rtkit package.


%package data
Summary: data components for the rtkit package.
Group: Data

%description data
data components for the rtkit package.


%package libexec
Summary: libexec components for the rtkit package.
Group: Default

%description libexec
libexec components for the rtkit package.


%package man
Summary: man components for the rtkit package.
Group: Default

%description man
man components for the rtkit package.


%package services
Summary: services components for the rtkit package.
Group: Systemd services
Requires: systemd

%description services
services components for the rtkit package.


%package tests
Summary: tests components for the rtkit package.
Group: Default
Requires: rtkit = %{version}-%{release}

%description tests
tests components for the rtkit package.


%prep
%setup -q -n rtkit-0.13
cd %{_builddir}/rtkit-0.13
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695142483
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1695142483
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rtkitctl

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.freedesktop.RealtimeKit1.xml
/usr/share/dbus-1/system-services/org.freedesktop.RealtimeKit1.service
/usr/share/dbus-1/system.d/org.freedesktop.RealtimeKit1.conf
/usr/share/polkit-1/actions/org.freedesktop.RealtimeKit1.policy

%files libexec
%defattr(-,root,root,-)
/usr/libexec/rtkit-daemon

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/rtkitctl.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/rtkit-daemon.service

%files tests
%defattr(-,root,root,-)
/usr/libexec/installed-tests/rtkit/rtkit-test
